# Generated by Django 5.0.1 on 2024-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
